### ISSUE TITLE
Charging cable release

### ISSUE THREAD

**Issue by JanEsders** [alandtse/tesla#341] opened 2022-11-10 21:53 UTC
Is it possible to release the charging cable after stopping charging?

I'd like to use this as an automation to not need to release the cable manually after leaving the house for work in the morning 👍

**Comment by cvwillegen** [comment] 2022-11-11 10:04
You can use ``cover.open_cover`` on the charger door entity, like this:

```
service: cover.open_cover
data: {}
target:
  entity_id: cover.xxx_charger_door
```

I'm not sure if the car won't re-lock the charging cable if it's left in place after unlocking it...

**Comment by wyx087** [comment] 2022-11-11 13:48
The `cover.x_charge_door `no longer work reliably in V3. Sometimes I get error along the line of "service unavailable" when calling open_cover. When this happens, I see the Lovelace UI shows open_cover button greyed out, only close_cover button is available. I've not found the pattern yet, but sometimes UI shows both open and close available to press. Only in this state, `cover.open_cover `service call will unlock the cable. 

Ideally, there is a button for cable unlock. Or the open cover button is made always available. 


For information, the car will re-lock the cable after 2 min. I've been able to reliably use pre-V3 `lock.unlock `command to do 2 things: 
- unlock cable as part of my morning routine, after front door open and shut. 
- repeatedly send unlock cable command less <2 minutes to get the car pre-condition using power from battery (when not in cheaper time-of-use tariff)

**Comment by alandtse** [comment] 2022-11-14 08:49
Dupe of #323

**Closed by alandtse** 2022-11-14 08:49 UTC
