### ISSUE TITLE
Error: Endpoint is only available on fleetapi

### ISSUE THREAD

**Issue by nickt444** [alandtse/tesla#844] opened 2024-01-30 22:34 UTC
I just noticed that the "Force data update" button is no longer working.
I assume this is related to the recent Tesla API changes, and I found a similar issue affecting Teslamate last week (https://github.com/teslamate-org/teslamate/issues/3629)
Everything else in the integration appears to be working.
Using latest 3.19.7

Getting "Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info" on call to https://owner-api.teslamotors.com/api/1/vehicles {}

2024-01-31 08:45:34.582 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547552274112] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tesla_custom/button.py", line 84, in async_press
    await self.update_controller(wake_if_asleep=True, force=True)
  File "/config/custom_components/tesla_custom/base.py", line 82, in update_controller
    await self.coordinator.controller.update(
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 734, in update
    cars = await self.get_vehicles()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 300, in get_vehicles
    return (await self.api("VEHICLE_LIST"))["response"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1319, in api
    return await self.__post_with_retries_except_unavailable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1351, in __post_with_retries_except_unavailable
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 165, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 217, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
2024-01-31 08:47:04.553 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-01-31 08:47:04.553 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 64220 Interval 60
2024-01-31 08:47:04.554 DEBUG (MainThread) [teslajsonpy.controller] 21894: online. Polling policy: normal. Update state: normal. Since last park: 10. Since last wake up: 64219. Idle interval: 600. shift_state: P sentry: False climate: True, charging: Disconnected 
2024-01-31 08:47:04.554 DEBUG (MainThread) [teslajsonpy.controller] 21894: Resetting last_parked_timestamp to: 1706651225 shift_state P
2024-01-31 08:47:04.554 DEBUG (MainThread) [teslajsonpy.controller] 21894: Skipping update with state online. Polling: True. Last update: 364 ago. Last parked: 0 ago. Last wake up 64219 ago. 
2024-01-31 08:47:04.554 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.002 seconds (success: True)
2024-01-31 08:47:04.742 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-01-31 08:47:04.742 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 64220 Interval 60
2024-01-31 08:47:04.743 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:22:08
2024-01-31 08:47:04.744 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:05.312 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:07.161 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:22:05
2024-01-31 08:47:07.162 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:07.379 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:09.788 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:22:03
2024-01-31 08:47:09.789 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:10.014 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:14.319 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:58
2024-01-31 08:47:14.320 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:14.529 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:14.552 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-01-31 08:47:19.744 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:53
2024-01-31 08:47:19.745 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:20.327 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:20.328 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 15.587 seconds (success: False)
2024-01-31 08:47:20.331 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 64235 Interval 60
2024-01-31 08:47:20.331 DEBUG (MainThread) [teslajsonpy.controller] 21894: online. Polling policy: normal. Update state: normal. Since last park: 15. Since last wake up: 64234. Idle interval: 600. shift_state: P sentry: False climate: True, charging: Disconnected 
2024-01-31 08:47:20.332 DEBUG (MainThread) [teslajsonpy.controller] 21894: Resetting last_parked_timestamp to: 1706651240 shift_state P
2024-01-31 08:47:20.332 DEBUG (MainThread) [teslajsonpy.controller] 21894: Skipping update with state online. Polling: True. Last update: 379 ago. Last parked: 0 ago. Last wake up 64234 ago. 
2024-01-31 08:47:20.332 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 5.780 seconds (success: True)
2024-01-31 08:47:25.549 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: True Time: 64241 Interval 60
2024-01-31 08:47:25.549 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:47
2024-01-31 08:47:25.550 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:26.216 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:27.857 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:45
2024-01-31 08:47:27.858 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:28.071 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:29.552 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-01-31 08:47:29.742 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-01-31 08:47:30.546 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:42
2024-01-31 08:47:30.546 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:30.753 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:35.652 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:37
2024-01-31 08:47:35.653 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:35.871 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:40.551 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 6:21:32
2024-01-31 08:47:40.552 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/vehicles {}
2024-01-31 08:47:40.759 DEBUG (MainThread) [teslajsonpy.connection] 412: {"response":null,"error":"Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info","error_description":""}
2024-01-31 08:47:40.760 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 64256 Interval 60
2024-01-31 08:47:40.761 DEBUG (MainThread) [teslajsonpy.controller] 21894: online. Polling policy: normal. Update state: normal. Since last park: 21. Since last wake up: 64255. Idle interval: 600. shift_state: P sentry: False climate: True, charging: Disconnected 
2024-01-31 08:47:40.761 DEBUG (MainThread) [teslajsonpy.controller] 21894: Resetting last_parked_timestamp to: 1706651261 shift_state P
2024-01-31 08:47:40.761 DEBUG (MainThread) [teslajsonpy.controller] 21894: Skipping update with state online. Polling: True. Last update: 400 ago. Last parked: 0 ago. Last wake up 64255 ago. 
2024-01-31 08:47:40.762 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 11.210 seconds (success: True)
2024-01-31 08:47:40.769 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547552274112]

**Comment by skipishere** [comment] 2024-01-30 22:58
Duplicate of #830

**Closed by skipishere** 2024-01-30 22:58 UTC
