### ISSUE TITLE
Location Tracking not working since 2023.38.x

### ISSUE THREAD

**Issue by NickWhitNTES** [alandtse/tesla#776] opened 2023-11-13 11:14 UTC
Hello.

I saw an open ticket for this, but it seems to have gone.  Location tracking still not working since tesla changed API.  Teslamate has this fixed, so it, I assume is possible?

**Comment by NickWhitNTES** [comment] 2023-11-13 11:15
Apologies, I found the original.
https://github.com/alandtse/tesla/issues/756

However, this is marked as fixed, yet I do not see tracking still?

**Comment by skipishere** [comment] 2023-11-13 11:15
Duplicate of https://github.com/alandtse/tesla/issues/756

**Closed by skipishere** 2023-11-13 11:15 UTC

**Comment by skipishere** [comment] 2023-11-13 11:18
@NickWhitNTES if you get latest version (v3.19.3) it should work (I've just upgraded my instance in Home Assistant and can see it working now)

**Comment by NickWhitNTES** [comment] 2023-11-13 11:19
> @NickWhitNTES if you get latest version (v3.19.3) it should work (I've just upgraded my instance in Home Assistant and can see it working now)

I think its not offered up in HACS yet?

**Comment by skipishere** [comment] 2023-11-13 11:21
By default, HACS will poll GitHub every so often to see if there are updates, it might be that this release happened after that poll. You can either wait til HACS does it, or force it to check by clicking the triple dot -> _Update information

![image](https://github.com/alandtse/tesla/assets/26724777/f4a71aa2-d3e1-4271-b3a5-d1dae6cffff1)

**Comment by NickWhitNTES** [comment] 2023-11-13 11:22
I have this version installed, and none of the Teslas added are showing location info on the "Location Tracker".

![image](https://github.com/alandtse/tesla/assets/82377682/1b36e679-4a61-4bd6-b4da-e0c5b500b5e6)
![image](https://github.com/alandtse/tesla/assets/82377682/b9330136-0a30-4226-bdb1-a5a0e7178173)

**Comment by skipishere** [comment] 2023-11-13 11:25
In which case, if you have the v3.19.3 installed, have rebooted HA and forced synced the data from the car after reboot then it would be worthwhile updating the issue with the bug information requested (version, logs, etc) so that people can investigate. Without that information it is an almost impossible task (esp if it is working for others)

**Comment by NickWhitNTES** [comment] 2023-11-13 11:32
Well, Have you Tried turning it off and on again? :)

Working now, thank you all!
