### ISSUE TITLE
Home Assistant warning about sentry mode switch/Sentry mode not correctly reflecting state

### ISSUE THREAD

**Issue by drjjr2** [alandtse/tesla#624] opened 2023-06-01 14:37 UTC
Seeing the following warning with 3.12.3.
Also of note is that the sentry mode switch is not in sync with the actual sentry mode setting in my car.

Warning in home-assistant.log after updating to 3.12.3. Sentry mode switch not reflecting sentry mode setting.

## Debug log

`2023-06-01 09:29:50.572 WARNING (MainThread) [homeassistant.helpers.entity] Entity switch.dons_model_3p_sentry_mode (<class 'custom_components.tesla_custom.switch.TeslaCarSentryMode'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`

**Comment by alandtse** [comment] 2023-06-01 16:32
Thanks. It's basically a dupe of #606

**Closed** 2023-06-01 16:32 UTC
