### ISSUE TITLE
Version 3.0.1 close frunk cover no response.

### ISSUE THREAD

**Issue by fishredleung** [alandtse/tesla#307] opened 2022-10-25 01:44 UTC
When pressing the close frunk cover button , fail message promt out.
Could you please change back close button to the same function as the frunk button as the Tesla App? 
It is the only way to trigger the frunk lock so that we could close the electric frunk

**Comment by shred86** [comment] 2022-10-25 02:04
Ah, sorry I see the issue. I’ll have to submit a PR for this in a couple days unless someone can get to this. The issue is I added the supported feature for closing the frunk but forgot to add the `async_close_cover` method to the `TeslaCarFrunk` class.

**Comment by fishredleung** [comment] 2022-10-25 02:14
thank you for your promt reply

**Closed** 2022-10-27 02:36 UTC
Labels: bug

**Comment by iainswarts** [comment] 2022-10-28 01:49
Is this an issue for anyone else still? I still can't close my electric trunk on 3.0.2.

**Comment by fishredleung** [comment] 2022-10-28 06:08
It works perfectly fine now

**Comment by subcritical71** [comment] 2022-10-28 14:11
> It works perfectly fine now

Same for me.

**Comment by iainswarts** [comment] 2022-11-01 03:57
Ah I found it! The `CoverEntity.CLOSE` is gated behind the `_car.powered_lift_gate` flag, in my case I've installed an aftermarket power trunk and frunk so I can no longer close either of them.

Can you add an option to override this somehow please?
