### ISSUE TITLE
Not able to send data to car to open windows/doors etc...

### ISSUE THREAD

**Issue by tekathan85** [alandtse/tesla#848] opened 2024-02-03 21:51 UTC
Hello all, 
I just installed the addon. I am able to see the car and its pulling data every 11 min or so. 
I am not able to send the car any info such as open windows/doors etc.. 
Anyone know what I might be missing?

Thanks

**Comment by darek-margas** [comment] 2024-02-03 22:26
> Anyone know what I might be missing?

The new API

**Comment by plipof** [comment] 2024-02-03 23:21
Same issue here. Unable to send any commands. Logs show fleetapi errors. Flash lights, horn, nothing working.

**Comment by alandtse** [comment] 2024-02-04 01:45
Dupe of #774

**Closed by alandtse** 2024-02-04 01:45 UTC
