### ISSUE TITLE
Failed to set set up - HA logs have TypeError: ServiceRegistry.async_register() got an unexpected keyword argument 'supports_response' after update

### ISSUE THREAD

**Issue by dickon** [alandtse/tesla#801] opened 2023-12-19 15:57 UTC
Tesla Custom ingeration 3.19.3
HACS 2023.6.1

After updating via HACS I get "Failed to set up" and this in the HA logs:

```
Error setting up entry dickon.reed@gmail.com for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 144, in async_setup_entry
    async_setup_services(hass)
  File "/config/custom_components/tesla_custom/services.py", line 61, in async_setup_services
    hass.services.async_register(
TypeError: ServiceRegistry.async_register() got an unexpected keyword argument 'supports_response'
```

**Comment by gjhw** [comment] 2023-12-22 12:22
I've just come across this too.  No idea what version I was using before but I just tried to upgraded to v3.19.3 and have the same issue as described above.  I'm running Home Assistant 2023.6.3 under docker.

**Comment by gjhw** [comment] 2023-12-22 12:26
Looks like this could be a duplicate of [https://github.com/alandtse/tesla/issues/786](url)

I note that we @dickon and me are both running 2023.6 and we need 2023.7 or above to support the 'supports_response' argument.  Upgrade HA now.....

**Comment by gjhw** [comment] 2023-12-22 12:57
For me, upgrading to 2023.7 has resolved this issue.

**Comment by alandtse** [comment] 2023-12-28 01:48
As explained by the linked issue, your ha is too old.

**Closed** 2023-12-28 01:48 UTC
