### ISSUE TITLE
Car being driven but entities do not update?

### ISSUE THREAD

**Issue by Lockie85** [alandtse/tesla#607] opened 2023-05-15 07:08 UTC
## Version of the custom_component

[v3.12.2](https://github.com/alandtse/tesla/releases/tag/v3.12.2)

## Describe the bug

When I physically wake the car, for example by driving it (for over 40 minutes). The HA Tesla integration doesn't appear to update. I.E. If I force reload the integration, then everything updates. Which I assume means the integration is working as it is getting an update. My polling_interval is set to the default time of 660 and Polling Policy: Normal (default). What could be causing this issue?

**Comment by alandtse** [comment] 2023-05-16 07:15
Dupe of #556

**Closed by alandtse** 2023-05-16 07:15 UTC
Labels: duplicate
