### ISSUE TITLE
Authentication Error: Need oauth credentials

### ISSUE THREAD

**Issue by premanandc** [alandtse/tesla#49] opened 2021-09-29 00:31 UTC
## Describe the bug
Trying to configure the Tesla custom integration using the exact steps as described here: https://community.home-assistant.io/t/tesla-integration-not-working/274817/172 
Please look at the exact reply referenced above.

## Debug log
```text
2021-09-28 14:25:44 ERROR (MainThread) [custom_components.tesla_custom.config_flow] Authentication error: Need oauth credentials 
```

**Comment by alandtse** [comment] 2021-09-29 00:58
Dupe of #36

**Closed by alandtse** 2021-09-29 00:58 UTC
Labels: duplicate
