### ISSUE TITLE
Climate Entity

### ISSUE THREAD

**Issue by Siggy101** [alandtse/tesla#1028] opened 2024-08-08 12:14 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.0

### Version of the Tesla car software

2024.26.3.1

### Model

Model S 100D

### Current Behavior

Error in HA log:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:365
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 14:08:37 (1 occurrences)
Last logged: 14:08:37

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues

### Expected Behavior

Error in HA log:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:365
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 14:08:37 (1 occurrences)
Last logged: 14:08:37

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues

### Debug logs

```true
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:365
integration: Climate (documentation, issues)
First occurred: 14:08:37 (1 occurrences)
Last logged: 14:08:37

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
```

**Comment by skipishere** [comment] 2024-08-08 20:50
Duplicate of #854

**Closed** 2024-08-08 20:49 UTC
Labels: triage, car

**Comment by Siggy101** [comment] 2024-08-09 08:00
> Duplicate of #854

I'm so sorry that I missed that issue in my search.  Happy to have this once closed and I will follow 854 instead.
Again, sorry for wasting your time.
