### ISSUE TITLE
Unit of odometer 

### ISSUE THREAD

**Issue by floow77** [alandtse/tesla#332] opened 2022-11-05 13:43 UTC
## Version of the custom_component

Tesla custom Integration: Version 3.0.2
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3

## Describe the bug

Unit of sensors. "Odometer" and "Range" is mi and not kms
How can I setup with unit kms ?

**Comment by alandtse** [comment] 2022-11-05 17:09
Dupe of #301

**Closed by alandtse** 2022-11-05 17:09 UTC
Labels: duplicate
