### ISSUE TITLE
total_increasing, but its state is not strictly increasingCar Issue: 

### ISSUE THREAD

**Issue by Joshuaharry120** [alandtse/tesla#838] opened 2024-01-26 21:46 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.19.5

### Version of the Tesla car software

N/A

### Model

Model Y

### Current Behavior

N/A

### Expected Behavior

N/A

### Debug logs

```true
2024-01-26 21:30:10.194 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.starship_energy_added from integration tesla_custom has state class total_increasing, but its state is not strictly increasing. Triggered by state 2.22 (2.24) with last_updated set to 2024-01-26T21:29:44.400869+00:00. Please create a bug report at https://github.com/alandtse/tesla/issues
```

### Anything else?

N/A

**Comment by alandtse** [comment] 2024-01-27 11:15
Dupe of #748

**Closed by alandtse** 2024-01-27 11:15 UTC
Labels: duplicate, triage, car

**Comment by austin20202020** [comment] 2024-02-10 18:05
2024-02-10 10:25:12.282 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.energy_added from integration tesla_custom has state class total_increasing, but its state is not strictly increasing. Triggered by state 15.81 (15.83) with last_updated set to 2024-02-10T16:22:45.207250+00:00. Please create a bug report at https://github.com/alandtse/tesla/issues

**Comment by skipishere** [comment] 2024-02-10 19:42
This is a duplicate, see the linked issue above
