### ISSUE TITLE
My car suddenly started to have bad vampire drain. 

### ISSUE THREAD

**Issue by JAFC-BandO** [alandtse/tesla#778] opened 2023-11-13 18:52 UTC
I have the latest version og Teala and the Intergration in HA. 

So after Saterday (2 days ago) my car keeps waking up every 30 min. And I have no idea why it's doing it, I didn't change anything etc. So am guessing it's either this integration or I'm not sure. Also turns off the Pull at night via HA but still didn't do anything

**Comment by skipishere** [comment] 2023-11-13 19:03
Without filling in the issue template (eg logs) then we have nothing to go on.
The logs would show if the integration was the cause of the vampire drain if it was at fault/being triggered.

I'll close this for now but if you come back with the required information we can reopen and potentially investigate

**Closed by skipishere** 2023-11-13 19:03 UTC
