### ISSUE TITLE
implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off

### ISSUE THREAD

**Issue by mrbrdo** [alandtse/tesla#949] opened 2024-04-24 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.20.6

### Version of the Tesla car software

2023.44.1

### Model

Model 3

### Current Behavior

Logs say to report this here

### Expected Behavior

Logs say to report this here

### Debug logs

```true
Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
```
```


### Anything else?

_No response_

**Comment by skipishere** [comment] 2024-04-24 23:42
Duplicate of #854

**Closed** 2024-04-24 23:42 UTC
Labels: triage, car
