### ISSUE TITLE
Powerwall Issue: Devices Becoming Unavailable After X Time - Reload Fixes the Issue

### ISSUE THREAD

**Issue by ziptbm** [alandtse/tesla#937] opened 2024-04-04 01:08 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.20.5

### Version of the Powerwall Gateway software

24.4.0 0fe780c9

### Model

2

### Current Behavior

I only have Powerwalls now, no cars.   The device reports values for a bit and controls (e.g. after a restart) and then within an hour or two, it becomes unavailable.  If I reload the integration, it works for an hour and then goes unavailable again.

### Expected Behavior

For them to stay available, like it has for years.

### Debug logs

```true
I took a debug log, but I could use a pointer on how to filter out the PII information from it.  I can see things in it from an initial scan that appears to be personal information I would not like to share so broadly.  Please advise on what specific pieces to extract and share here.
```

**Comment by skipishere** [comment] 2024-04-04 08:47
Duplicate of #922

**Closed** 2024-04-04 08:47 UTC
Labels: triage

**Comment by ziptbm** [comment] 2024-04-04 13:28
> Duplicate of #922

I commented in that issue, but I wasn't sure it was the same.  Thank you for confirming.
