### ISSUE TITLE
Did not find custom-components/tesla (0)

### ISSUE THREAD

**Issue by fastender** [alandtse/tesla#100] opened 2021-11-17 18:09 UTC
Newest Version of the custom_component

```yaml
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/data.py:177 
Integration: HACS (documentation, issues) 
First occurred: 19:07:00 (1 occurrences) 
Last logged: 19:07:00

Did not find custom-components/tesla (0)

```

I am not able to delete the integration. I get this error message.

**Comment by alandtse** [comment] 2021-11-19 05:20
That is reporting an issue with HACS. Did you install it as a custom repository first? Something looks like it broke if it's also a default repo. https://github.com/hacs/integration/issues/2296

**Comment by alandtse** [comment] 2021-11-20 03:36
It's confirmed it's an HACS issue. Closing.

**Closed by alandtse** 2021-11-20 03:36 UTC
