### ISSUE TITLE
sensor.home_energy_gateway_battery intermittently cycles between state values of 0% and the actual value. 

### ISSUE THREAD

**Issue by AlohaFlyer** [alandtse/tesla#706] opened 2023-08-30 21:41 UTC
[home-assistant_tesla_custom_2023-08-30T21-45-21.984Z.log](https://github.com/alandtse/tesla/files/12480367/home-assistant_tesla_custom_2023-08-30T21-45-21.984Z.log)

## Version of the custom_component
v3.16.1

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

sensor.home_energy_gateway_battery intermittently cycles between state values of 0% and the actual value. 

## Debug log

```text

**Comment by alandtse** [comment] 2023-09-04 07:27
Dupe of #475

**Closed by alandtse** 2023-09-04 07:27 UTC
Labels: duplicate
