### ISSUE TITLE
3.0 Throwing EnergySites KeyError

### ISSUE THREAD

**Issue by bassrock** [alandtse/tesla#290] opened 2022-10-22 16:57 UTC
## Version of the custom_component

3.0

## Configuration

Setup with a tesla account with only Energy sites checked

## Describe the bug

The integration does not start due to a key issue loading the site data. 

(Note, one of my sites is pre tesla owning Solarcity which seems to produce interesting data.)

## Debug log

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla_custom/__init__.py", line 346, in _async_update_data
    return await self.controller.update()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 964, in update
    return any(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 836, in _get_and_process_site_data
    if not self._grid_status_unknown[energysite_id] and (
KeyError: 1234 <- energy site id.

```

**Comment by shred86** [comment] 2022-10-22 17:04
I _think_ this is being caused by another issue I just found and submitted a [PR](https://github.com/alandtse/tesla/pull/288) for. Once we get it merged into dev, if you could install the dev version to test it, that would be helpful.

**Comment by bassrock** [comment] 2022-10-22 17:18
@shred86 unfortunately still showing up with that latest dev version.

**Comment by alandtse** [comment] 2022-10-22 17:59
This is an issue in teslajsonpy with an uninitialized key.

**Closed** 2022-10-22 18:14 UTC
Labels: bug, teslajsonpy
