### ISSUE TITLE
HVAC type errors

### ISSUE THREAD

**Issue by greggo74** [alandtse/tesla#1046] opened 2024-09-28 10:45 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.1

### Version of the Tesla car software

2024.26.7 & 2024.32.3

### Model

Model 3 2024

### Current Behavior

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:370
integration: Climate (documentation, issues)
First occurred: 8:35:06 PM (2 occurrences)
Last logged: 8:35:06 PM

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues

### Expected Behavior

No errors in the logs

### Debug logs

```true
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:370
integration: Climate (documentation, issues)
First occurred: 8:35:06 PM (2 occurrences)
Last logged: 8:35:06 PM

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
```

**Comment by skipishere** [comment] 2024-09-28 10:57
Duplicate of #854

**Closed** 2024-09-28 10:57 UTC
Labels: triage, car

**Comment by greggo74** [comment] 2024-09-28 11:16
Sorry, didn't see the other one amongst the search results.
