### ISSUE TITLE
no more battery soc sensor in v3.15 ??

### ISSUE THREAD

**Issue by BartJocque** [alandtse/tesla#662] opened 2023-07-08 07:08 UTC
I had no more battery soc sensor in v3.15 and had to roll back to v314

**Comment by gbuktenica** [comment] 2023-07-08 07:10
I am getting this with 
2023.6.1 and 2023.7.1

**Comment by sumur1au** [comment] 2023-07-08 07:18
I also don't have the battery sensor with below software versions and I also not able to call the force data update as well (Error: Failed to call service button/press. connection lost).

Model Y: Firmware: 2023.20.4.1 f65fa7dd0232
Home Assistant: 2023.7.1
Integration:3.15

**Comment by gbuktenica** [comment] 2023-07-08 07:32
@sumur1au I was able to force an update after a restart of HA

**Comment by sumur1au** [comment] 2023-07-08 08:09
Thanks, I rolled back and restarted as you suggested. Working now :)

**Comment by alandtse** [comment] 2023-07-08 09:26
Dupe of #661 which is the root cause.

**Closed by alandtse** 2023-07-08 09:26 UTC
Labels: duplicate
