### ISSUE TITLE
Emissions test button not working

### ISSUE THREAD

**Issue by MatthewGCampbell** [alandtse/tesla#955] opened 2024-04-28 00:58 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.21.0

### Version of the Tesla car software

2024.3.15

### Model

Model 3 highland

### Current Behavior

I have the emissions test button is the diagnostic section but when clicked I get “ Failed to call service button/press. unknown error” and the vehicle doesn’t fart

### Expected Behavior

When the button is pushed the vehicle should fart

### Debug logs

```true
Not sure, couldn’t exactly find a log related to the issue
```

### Anything else?

Unsure if it got removed from the API

**Comment by skipishere** [comment] 2024-04-28 06:55
Duplicate of #751

**Closed** 2024-04-28 06:55 UTC
Labels: duplicate, car
