### ISSUE TITLE
Tesla doesn't wake up when set HVAC to heat_cool

### ISSUE THREAD

**Issue by dawiinci** [alandtse/tesla#162] opened 2022-03-19 07:55 UTC
If I set this (or probably any) command and the car is at sleep, it won't activate. It will however, wake the car. If I send the command again it activates HVAC.

It should first wake the car and then send the command.

Can I wake the car without sending commands? Because the underlying python script allows for that.

**Comment by alandtse** [comment] 2022-03-19 19:42
Please provide logs for teslajsonpy showing the attempt to wake up.

**Comment by jherby2k** [comment] 2022-03-29 13:54
this seems to be an API quirk - i wrote a script to wake up the car if its asleep. just call it before setting HVAC.

```yaml
alias: Wake up car
sequence:
  - condition: state
    entity_id: binary_sensor.sonic_online_sensor
    state: 'off'
  - service: tesla_custom.api
    data:
      command: WAKE_UP
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.<name>_online_sensor'', ''id'') }}'
  - wait_template: '{{ is_state(''binary_sensor.<name>_online_sensor'', ''on'') }}'
    timeout: '2:00'
mode: single
icon: mdi:car-connected
```

**Comment by dawiinci** [comment] 2022-04-20 20:21
I do something similar. Actually set the hvac, then check for connected state and send it again. Might be a bit quicker.

**Comment by alandtse** [comment] 2022-04-23 03:06
The reason I asked for logs is the component does try to wake up the car on this change. I tested it and don't see this issue. Obviously, it may fail if the car isn't responding or Tesla is busy. But without logs, I can't do anything.

See `wake_if_asleep=True`
https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/homeassistant/climate.py#L129-L141

**Comment by dawiinci** [comment] 2022-04-24 10:29
I will check if this happens again.

**Comment by jherby2k** [comment] 2022-04-24 14:10
I see it wake the car up too, but it doesn't start the HVAC unless you call
it again after its awake. Is that what you mean?

**Comment by dawiinci** [comment] 2022-04-24 16:52
That was exactly the behavior that lead me to write this issue. However, today it worked without setting the HVAC a second time. Not sure how consistent this is, but the car was indeed alway woken up.

**Comment by alandtse** [comment] 2022-04-24 18:32
It's a bug if it doesn't reissue the command. However, without teslajsonpy logs, I can't see the underlying wakeup/API calls.

**Comment by dawiinci** [comment] 2022-04-30 10:28
I am not sure if this is an issue of Tesla oder the plugin. I could wake the car manually:

`Error executing service: <ServiceCall climate.set_hvac_mode (c:8cd36783b7e1c721006005b15c17698a): hvac_mode=heat_cool, entity_id=['climate.tesla_hvac_climate_system']>
Traceback (most recent call last):
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1652, in catch_exceptions
    await coro_or_task
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/Users/server/.homeassistant-config/custom_components/tesla_custom/tesla_device.py", line 35, in wrapped
    result = await func(*args, **kwargs)
  File "/Users/server/.homeassistant-config/custom_components/tesla_custom/climate.py", line 100, in async_set_hvac_mode
    await self.tesla_device.set_status(True)
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/teslajsonpy/homeassistant/climate.py", line 133, in set_status
    data = await self._controller.api(
  File "/Users/server/.homeassistant/lib/python3.9/site-packages/teslajsonpy/controller.py", line 247, in wake_up
    raise RetryLimitError("Reached retry limit; aborting wake up")
teslajsonpy.exceptions.RetryLimitError`

Maybe the retry limit is too low in some cases.

**Comment by alandtse** [comment] 2022-04-30 17:46
It tries 5 times to wake up your car. We're trying not to get you banned from Tesla so we're unlikely to change it.

**Comment by dawiinci** [comment] 2022-05-01 20:16
Maybe you could extend the time between the retries.

**Comment by alandtse** [comment] 2022-05-01 21:29
People already complain it takes too long to wake up and they just reissue the command again. Unfortunately, your issue is an edge case where there isn't really a good programmatic solution. As the logs show it's working as intended, I'll close this out.

**Closed by alandtse** 2022-05-01 21:29 UTC
