### ISSUE TITLE
Tesla M3 work, but "Include Energy Sites" no

### ISSUE THREAD

**Issue by denisjoshua** [alandtse/tesla#331] opened 2022-11-05 13:13 UTC
-->

## Version of the custom_component
- last version of component (I don't know where to see the version) 

here is the log on Home Assistant (debug) 
```
2022-11-05 13:54:23.154 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/powerwalls/STExxxxxxx-xxxxx {}
2022-11-05 13:54:23.536 DEBUG (MainThread) [teslajsonpy.connection] 408: {"response":null,"error":"https://powergate.prd.sn.tesla.services:443/api/powerwalls/xxxxxxx-01-B--T1xxxxxxxxxxx/fullstatus => Can't get recent status from the battery","error_description":""}
2022-11-05 13:54:23.536 DEBUG (MainThread) [teslajsonpy.controller] Exception: vehicle_unavailable
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
2022-11-05 13:54:23.537 ERROR (MainThread) [custom_components.tesla_custom] Unable to communicate with Tesla API: VEHICLE_UNAVAILABLE
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
api(('BATTERY_DATA',) {'path_vars': {'battery_id': 'STExxxxxxxx-xxxxx'}})
```

here is the log of the component
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 1:46:41 PM (1 occurrences)
Last logged: 1:46:41 PM

Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/base.py, line 71: if self.hass.config.units.is_metric


2022-11-05 13:46:29.272 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-05 13:46:41.228 DEBUG (MainThread) [custom_components.tesla_custom] Connected to the Tesla API
2022-11-05 13:46:41.228 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:46:41.229 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:46:41.243 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that accesses the `is_metric` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for tesla_custom using this method at custom_components/tesla_custom/base.py, line 71: if self.hass.config.units.is_metric
2022-11-05 13:46:41.253 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:46:41.253 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:46:51.403 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:46:51.403 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:47:01.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:01.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:47:11.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:11.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:47:21.002 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:21.002 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:47:31.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:31.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:47:41.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:42.020 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 1.019 seconds (success: True)
2022-11-05 13:47:52.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:47:52.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:48:02.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:02.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:48:12.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:12.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:48:22.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:22.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:48:32.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:32.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:48:42.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:42.376 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.374 seconds (success: True)
2022-11-05 13:48:52.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:48:52.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:49:02.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:02.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:49:12.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:12.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:49:22.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:22.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:49:32.001 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:32.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:49:42.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:42.174 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.174 seconds (success: True)
2022-11-05 13:49:52.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:49:52.001 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:50:02.002 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:50:02.002 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:50:12.000 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-11-05 13:50:12.000 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.000 seconds (success: True)
2022-11-05 13:50:15.821 DEBUG (MainThread) [custom_components.tesla_custom] Unloaded entry for info@email.xxx
2022-11-05 13:54:01.477 DEBUG (MainThread) [custom_components.tesla_custom.config_flow] Credentials successfully connected to the Tesla API
2022-11-05 13:54:23.537 ERROR (MainThread) [custom_components.tesla_custom] Unable to communicate with Tesla API: VEHICLE_UNAVAILABLE
```

## Describe the bug
The issue is that If I install the components with only "Included Vehicles" the component is work 
But if I install the component with also "Include Energy Sites" it give me error. 

I have the Tesla M3 and Tesla Powerwall2 on the same account. 
Also I see it on the mobile phone. 

Thanks a lot 
Denis

**Comment by alandtse** [comment] 2022-11-05 17:08
Dupe of #315

**Closed by alandtse** 2022-11-05 17:08 UTC
Labels: duplicate

**Comment by denisjoshua** [comment] 2022-11-05 17:18
Yes... it's like my case... 
This issue can be close. 
Thanks a lot 
Denis
