### ISSUE TITLE
Failed to Setup - No devices or entities 

### ISSUE THREAD

**Issue by tannerwastaken** [alandtse/tesla#727] opened 2023-10-07 00:41 UTC
I've been using this integration for almost a year with no issues... today, all of the sudden, it stopped working. My family shares a Tesla account, and we have 3 vehicles and 1 powerwall on the account. For some reason, the integration states failed to Setup no devices or entities. I've already downgraded home assistant, as well as the integration version, and logged out/in a number of times to no avail. Note that every time I login, it says success and adds the account properly. Is this an issue with Tesla, the integration, new updates, or some combination? Also I will post logs, but I don't really know how. I'm sorry if this is a newbie question, but I enabled debugging through the integration and I just can't find where the logs are stored. Thank you.

**Comment by peter-mc** [comment] 2023-10-07 00:52
Same problem here, just says failed to set up, and none of the sensors are available..

**Comment by DavidPannellHome** [comment] 2023-10-07 00:53
Yep, I've been having issues for the last couple of days too.

**Comment by tannerwastaken** [comment] 2023-10-07 01:05
Geez, glad to know I'm not going insane... I thought I might be since it didn't seem like this issue was posted. Glad I wasted all day trying to troubleshoot 😂

**Comment by lyricnz** [comment] 2023-10-07 01:19
Me too

**Comment by tannerwastaken** [comment] 2023-10-07 02:16
> Me too. The logs (default level) say:
> 
> 2023-10-07 12:17:58.852 WARNING (MainThread) [teslajsonpy.controller] Unable to get battery data during setup, battery will still be added. 410: UNKNOWN_ERROR_410

I don't even have that in my supervisor logs...

**Comment by MikeatLorne** [comment] 2023-10-07 02:22
Mine is not working either
2023-10-07 13:13:04.852 WARNING (MainThread) [teslajsonpy.controller] Unable to get battery data during setup, battery will still be added. 410: UNKNOWN_ERROR_410
2023-10-07 13:13:20.443 ERROR (MainThread) [custom_components.tesla_custom] Unable to communicate with Tesla API: UNKNOWN_ERROR_410

normally very reliable

**Comment by SteveWin1** [comment] 2023-10-07 02:58
Same issue and same error in the logs as others. Gotta be something Tesla changed since it affected us all at the same time, right? Hopefully it can be corrected for.

**Comment by JetRangerMike** [comment] 2023-10-07 04:00
Same error for me (aka Unable to communicate with Tesla API: UNKNOWN_ERROR_410).  I've tried to revert to an earlier version of the integration and have reinstalled with new auth token.  Alas, no joy. :(

**Comment by syndanm** [comment] 2023-10-07 04:42
same

**Comment by purcell-lab** [comment] 2023-10-07 05:27
This is a duplicate of #724

**Closed** 2023-10-07 13:46 UTC
