### ISSUE TITLE
Battery sensor unavailable

### ISSUE THREAD

**Issue by ljungqvist** [alandtse/tesla#634] opened 2023-06-15 05:51 UTC
## Version of the custom_component
3.13.0

## Configuration
Tesla Model S 2017 SW 2.22.8.10.12

## Describe the bug

Since the last update the Battery sensor is unavailable. I have tried reloading the integration and restarting HA, but it doesn't help. I updated from 3.12.3, where the sensor was working.

## Debug log

I found nothing in the logs related to the battery sensor (just a lot related to https://github.com/alandtse/tesla/issues/633, which I am also experiencing).

**Comment by alandtse** [comment] 2023-06-15 08:20
Dupe of #633. Please follow that.

**Closed by alandtse** 2023-06-15 08:20 UTC
Labels: duplicate

**Comment by ljungqvist** [comment] 2023-06-15 08:30
> Dupe of #633. Please follow that.

How is this a duplicate? Or do you mean that the Steering wheel heating issue is causing this issue, so solving the steering wheel issue will solve the battery issue as well?
