### ISSUE TITLE
Hvac

### ISSUE THREAD

**Issue by Schelin78** [alandtse/tesla#1056] opened 2024-10-19 11:33 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

V3.24.1

### Version of the Tesla car software

2024.32.7

### Model

Model S

### Current Behavior

Warning in HA

### Expected Behavior

No warning

### Debug logs

```true
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:371
integration: Climate (documentation, issues)
First occurred: 13:22:02 (3 occurrences)
Last logged: 13:22:06

Entity None (<class 'custom_components.ebeco.climate.EbecoClimateDevice'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/joggs/home_assistant_ebeco/issues
Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
```

**Comment by skipishere** [comment] 2024-10-19 17:04
Duplicate of #854

**Closed** 2024-10-19 17:04 UTC
Labels: triage, car
