### ISSUE TITLE
Powerwall state of charge %age sensor is extremely jittery - causes automation issues

### ISSUE THREAD

**Issue by ChrisJ60** [alandtse/tesla#600] opened 2023-05-07 08:38 UTC
## Version of the custom_component

3.12.1

## Configuration

Nothing special in config or showing in HA logs.

## Describe the bug

The values returned by the Powerwall SoC %age sensor (sensor.<battery_name>_battery) are very jittery. I have my own custom sensor (based on command_line) which leverages my Powerwalls monitor (which polls the Powerwall once every 20 seconds) and that sensor does not show any jitter.

The degree of jitter is such that it makes fine grained automations impossible. Can the jitter be eliminated (or greatly reduced) for this sensor in order to make it usable? For now I am just using my custom sensor which works fine.

## Debug log

Debug logs don't show anything useful sadly.

Here are screenshots of the integration's sensor values (Jenkins Family Battery) versus my custom sensor (Powerwall Current SoC) for the same periods:

<img width="565" alt="Tesla Integration - Battery SoC" src="https://user-images.githubusercontent.com/2779798/236667037-c4699fbb-c9bb-4d09-8547-f1f08b8325a0.png">

<img width="561" alt="Custom Sensor - Powerwall SoC" src="https://user-images.githubusercontent.com/2779798/236667054-8ffe5b87-9f55-46c0-85c7-bc63b5d9a0c1.png">

**Comment by jaymunro** [comment] 2023-05-25 07:01
This is a duplicate of #475 which in turn is a duplicate of #296.

**Comment by jaymunro** [comment] 2023-10-07 22:57
This looks to be resolved by #724

**Closed** 2023-10-08 01:04 UTC
