### ISSUE TITLE
Polling switch - state not retained after HA restart

### ISSUE THREAD

**Issue by bdr99** [alandtse/tesla#39] opened 2021-09-16 05:10 UTC
## Version of the custom_component

1.0.0

## Configuration

N/A

## Describe the bug

If I turn off the polling switch for my car and then restart HA, the polling switch is turned back on. I would expect the state to be retained between HA restarts.

## Debug log

N/A

**Comment by alandtse** [comment] 2021-09-16 06:20
Not a bug but a result of a core rejection of allowing us to save states. We can consider adding it in as an enhancement.

**Comment by bdr99** [comment] 2021-09-16 23:14
So this change was previously submitted and rejected by HA core? Do you have a link to that PR?

**Comment by alandtse** [comment] 2021-09-17 02:35
https://github.com/home-assistant/core/pull/31877

**Comment by SeraphimSerapis** [comment] 2021-09-18 17:43
Pardon my ignorance, but isn't this something that can be handled by disabling manual polling for the integration? This was added in [2021.6](https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration).

It does come with the downside that it'll apply to all devices in an integration but other than that, it should do the trick.

**Comment by bdr99** [comment] 2021-09-29 20:37
@SeraphimSerapis That's a good point. If this feature works, then I don't think we even need the polling switch entity. I'm not in a position to validate this right now, can anyone else test if this works?

**Comment by alandtse** [comment] 2021-09-29 20:42
Polling switch is by car. The HA feature is per integration. Some people have multiple cars.

**Comment by SeraphimSerapis** [comment] 2021-09-29 21:08
> Polling switch is by car. The HA feature is per integration. Some people have multiple cars.

Yeah, I get that downside. It's not great for people with multiple cars -- it's only a workaround for those with a single Tesla.

**Comment by alandtse** [comment] 2022-10-22 09:15
Closing given 3.0 rewrite.

**Closed by alandtse** 2022-10-22 09:15 UTC
Labels: enhancement, help wanted

**Comment by bdr99** [comment] 2022-10-22 12:18
Is this fixed in 3.0.0? I don't see it mentioned in the changelog.

**Comment by jonnylangefeld** [comment] 2022-10-23 23:13
Following, because I'm curious as well. I haven't updated just yet.
