### ISSUE TITLE
Warning from log

### ISSUE THREAD

**Issue by enoch85** [alandtse/tesla#969] opened 2024-05-21 15:24 UTC
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.21.0

### Version of the Tesla car software

2024.8.9

### Model

Model 3 Long Range

### Current Behavior

```
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:302
integration: Sensor (documentation, issues)
First occurred: 03:05:10 (1 occurrences)
Last logged: 03:05:10

Entity sensor.energy_added from integration tesla_custom has state class total_increasing, but its state is not strictly increasing. Triggered by state 9.57 (9.7) with last_updated set to 2024-05-21T01:00:47.462351+00:00. Please create a bug report at https://github.com/alandtse/tesla/issues
```

### Expected Behavior

No error

### Debug logs

```true
See above
```

**Comment by skipishere** [comment] 2024-05-21 15:42
Duplicate of https://github.com/alandtse/tesla/issues/748

**Closed by skipishere** 2024-05-21 15:42 UTC
Labels: car
