### ISSUE TITLE
Sentry mode not activated via script

### ISSUE THREAD

**Issue by elic1973** [alandtse/tesla#129] opened 2022-01-11 07:45 UTC
## Version of the custom_component

v1.4.0

## Configuration

SCRIPT :
alias: Turn On Sentry Mode
sequence:
  - service: tesla_custom.api
    data:
      command: SET_SENTRY_MODE
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.julia_online_sensor'', ''id'') }}'
          'on': true
        wake_if_asleep: true
mode: single

## Describe the bug

Running the script and getting response 200. Messages looks OK.
But the actual result is that the Sentry mode is not "On" when trying to get closer to the car (no BT device near the car).
The car was on status "Online".

## Debug log

LOG:
2022-01-11 09:40:48 INFO (MainThread) [homeassistant.components.script.turn_on_sentry_mode] Turn On Sentry Mode: Running script sequence
2022-01-11 09:40:48 INFO (MainThread) [homeassistant.components.script.turn_on_sentry_mode] Turn On Sentry Mode: Executing step call service
2022-01-11 09:40:48 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 44 days, 19:50:13
2022-01-11 09:40:48 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/XXXXXXXXXXXXX/command/set_sentry_mode {}
2022-01-11 09:40:52 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"reason":"","result":true}}

```text

Add your logs here.

```

**Comment by alandtse** [comment] 2022-01-11 09:55
Compare it to if you use the actual UI and confirm the switch is also not working. After enabling or disabling, check the official app and confirm the behavior.

**Comment by elic1973** [comment] 2022-01-11 10:54
I used these iOS shortcuts with the same token and it is working.
https://github.com/dburkland/tesla_ios_shortcuts/blob/master/README.md

**Comment by elic1973** [comment] 2022-01-13 07:16
I manage to find the difference, with the access token the sentry mode (iOS shortcuts) is activated but with the refresh token (from your app) it does not...
Now I have no idea why this is happening. 
Any thoughts from your side @alandtse ?

**Comment by alandtse** [comment] 2022-01-13 07:56
I can't reproduce the issue you're reporting. The service call and switch works fine for both my Model 3 and my Model Y.
```
service: tesla_custom.api
data:
  command: SET_SENTRY_MODE
  parameters:
    path_vars:
      vehicle_id: '{{ state_attr(''binary_sensor.everest_online_sensor'', ''id'') }}'
    on: false
    wake_if_asleep: true
```

Any changes I make whether through the UI or switch results in the official Tesla app updating within a few seconds. Obviously, changes to the Tesla app don't instantly appear in HA since it is on a poll. However, changes within HA appear instantaneously.

**Comment by alandtse** [comment] 2022-10-22 09:15
Closing given 3.0 rewrite.

**Closed by alandtse** 2022-10-22 09:15 UTC
