### ISSUE TITLE
Scheduled charging and departure

### ISSUE THREAD

**Issue by larstobi** [alandtse/tesla#437] opened 2022-12-15 16:52 UTC
It would be great to have the abilty to get and set scheduled charging and departure.

The features was merged in the upstream lib last week: https://github.com/zabuldon/teslajsonpy/pull/360

**Comment by InTheDaylight14** [comment] 2022-12-15 19:42
Duplicate of https://github.com/alandtse/tesla/issues/164

Also see [Wiki](https://github.com/alandtse/tesla/wiki/Scheduled-Charging-and-Departure)

**Closed** 2022-12-15 23:38 UTC
Labels: duplicate
