### ISSUE TITLE
HACS reports 'Did not find alandtse/tesla (362700564)'

### ISSUE THREAD

**Issue by FalconUK** [alandtse/tesla#126] opened 2021-12-30 21:39 UTC
Please bear with me, this is the first time I've done this......

Context:
I am attempting to upgrade to HA 2021.12.7.
HA OS running on a Pi4.
Supervisor 2021.12.2

The log reports;
```
This error originated from a custom integration.
Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/data.py:181
Integration: HACS (documentation, issues)
First occurred: 20:52:17 (1 occurrences)
Last logged: 20:52:17

Did not find alandtse/tesla (362700564)
```

The HACS page in HA shows that that 'Tesla' is a new repository, always, even after I attempt to download it.

/config/custom_components/tesla_custom/const.py reports that the version is 1.4.0, so it looks like the latest version has downloaded?

## Version of the custom_component

`VERSION = "1.4.0"`

## Configuration
No YAML configuration used for the custom component.

```
logger:
    default: critical
    logs:
        homeassistant.loader: debug
        custom_components.hacs: debug
        custom_components.tesla_custom: debug
```

## Describe the bug

The custom integration appears to be stuck, it isn't loaded, yet keeps trying to download the same update again and again.

If I roll back to 2021.11.5, everything returns to functioning correctly.

## Debug log

This is after trying to download the repository again, even though it has already downloaded;

`2021-12-30 21:45:34 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 0 ('NoneType' object has no attribute 'data')`

This is after a server restart
```
2021-12-30 21:36:48 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-30 21:36:48 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-30 21:36:48 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-30 21:36:49 INFO (SyncWorker_4) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2021-12-30 21:36:49 INFO (SyncWorker_2) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2021-12-30 21:36:49 INFO (SyncWorker_3) [homeassistant.loader] Loaded camera from homeassistant.components.camera
2021-12-30 21:36:49 INFO (SyncWorker_2) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2021-12-30 21:36:50 INFO (SyncWorker_3) [homeassistant.loader] Loaded panel_custom from homeassistant.components.panel_custom
2021-12-30 21:36:50 INFO (SyncWorker_1) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
2021-12-30 21:36:51 INFO (SyncWorker_4) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2021-12-30 21:36:51 INFO (SyncWorker_2) [homeassistant.loader] Loaded stt from homeassistant.components.stt
2021-12-30 21:36:51 INFO (SyncWorker_1) [homeassistant.loader] Loaded tts from homeassistant.components.tts
2021-12-30 21:36:53 INFO (SyncWorker_4) [homeassistant.loader] Loaded rpi_gpio from homeassistant.components.rpi_gpio
2021-12-30 21:36:54 INFO (SyncWorker_1) [homeassistant.loader] Loaded command_line from homeassistant.components.command_line
2021-12-30 21:36:55 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.18.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2021-12-30 21:36:55 INFO (SyncWorker_2) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2021-12-30 21:36:55 INFO (SyncWorker_2) [homeassistant.loader] Loaded plex from homeassistant.components.plex
2021-12-30 21:36:57 INFO (SyncWorker_6) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Configuration type: config_entry
2021-12-30 21:36:57 INFO (SyncWorker_4) [homeassistant.loader] Loaded number from homeassistant.components.number
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Loaded 11 tasks
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Scheduling the hello_world task to run every 364 days, 0:00:00
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.SETUP
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: clear_old_storage
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: check_constrains
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: setup_websocket_api
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task setup_websocket_api took 0.00 seconds to complete
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: activate_categories
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Enable category: integration
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Enable category: theme
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task activate_categories took 0.00 seconds to complete
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: restore_data
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: setup_sensor
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task setup_sensor took 0.00 seconds to complete
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: setup_frontend
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] LovelaceMode.STORAGE mode, cache for /hacsfiles/: True
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task setup_frontend took 0.04 seconds to complete
2021-12-30 21:36:57 INFO (MainThread) [custom_components.hacs] Executing task: verify_api
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task clear_old_storage took 0.13 seconds to complete
2021-12-30 21:36:57 DEBUG (MainThread) [custom_components.hacs] Task check_constrains took 0.13 seconds to complete
2021-12-30 21:36:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded stream from homeassistant.components.stream
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Restore started
2021-12-30 21:36:58 ERROR (MainThread) [custom_components.hacs] Did not find alandtse/tesla (362700564)
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Restore done
2021-12-30 21:36:58 DEBUG (MainThread) [custom_components.hacs] Task restore_data took 0.95 seconds to complete
2021-12-30 21:36:58 DEBUG (MainThread) [custom_components.hacs] Can update 260 repositories
2021-12-30 21:36:58 DEBUG (MainThread) [custom_components.hacs] Task verify_api took 1.03 seconds to complete
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Executing task: load_hacs_repository
2021-12-30 21:36:58 DEBUG (MainThread) [custom_components.hacs] Task load_hacs_repository took 0.00 seconds to complete
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-12-30 21:36:58 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-12-30 21:37:00 INFO (SyncWorker_0) [homeassistant.loader] Loaded fan from homeassistant.components.fan
2021-12-30 21:37:00 INFO (SyncWorker_4) [homeassistant.loader] Loaded light from homeassistant.components.light
2021-12-30 21:37:01 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-12-30 21:37:01 INFO (MainThread) [custom_components.hacs] Executing task: load_hacs_repository
2021-12-30 21:37:01 DEBUG (MainThread) [custom_components.hacs] Task load_hacs_repository took 0.00 seconds to complete
2021-12-30 21:37:01 INFO (SyncWorker_4) [homeassistant.loader] Loaded spotify from homeassistant.components.spotify
2021-12-30 21:37:01 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Got 137 elements for removed
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Can update 260 repositories, items in queue 3
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Checking out tasks to execute
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Starting queue execution for 3 tasks
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Got 67 elements for theme
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Got 625 elements for integration
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Got 240 elements for plugin
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Queue execution finished for 3 tasks finished in 0.61 seconds
2021-12-30 21:37:02 DEBUG (MainThread) [custom_components.hacs] Starting recurring background task for installed repositories
2021-12-30 21:37:03 DEBUG (MainThread) [custom_components.hacs] Checking out tasks to execute
2021-12-30 21:37:03 DEBUG (MainThread) [custom_components.hacs] Starting queue execution for 1 tasks
2021-12-30 21:37:03 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> Getting repository information
2021-12-30 21:37:03 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> Running checks against v2.4.6
2021-12-30 21:37:04 DEBUG (MainThread) [custom_components.hacs] 'trigger' is undefined
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Queue execution finished for 1 tasks finished in 6.90 seconds
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Recurring background task for installed repositories done
2021-12-30 21:37:10 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-12-30 21:37:10 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-12-30 21:37:11 INFO (SyncWorker_6) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2021-12-30 21:37:11 INFO (SyncWorker_9) [homeassistant.loader] Loaded ffmpeg from homeassistant.components.ffmpeg
```

**Comment by alandtse** [comment] 2021-12-31 20:27
Dupe of #122

**Closed** 2021-12-31 20:27 UTC
Labels: duplicate

**Comment by FalconUK** [comment] 2021-12-31 20:42
I'm sorry, I have only just found the 'Closed' tab!

Thanks for your great work.

**Comment by FalconUK** [comment] 2021-12-31 20:45
Has been reported and fixed.

https://github.com/hacs/integration/issues/2383
