### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by luisiam** [alandtse/tesla#818] opened 2024-01-10 23:30 UTC
## Version of the custom_component

v3.19.5
## Configuration

```yaml
N/A
```

## Describe the bug

I am running HA 2024.1.2 with Tesla solar panel only. Getting a few deprecation warnings from the log.

## Debug log

```text

PRESSURE_BAR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.BAR instead, please create a bug report at https://github.com/alandtse/tesla/issues
PRESSURE_PSI was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.PSI instead, please create a bug report at https://github.com/alandtse/tesla/issues
SPEED_MILES_PER_HOUR was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.MILES_PER_HOUR instead, please create a bug report at https://github.com/alandtse/tesla/issues
TEMP_CELSIUS was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/alandtse/tesla/issues
ELECTRIC_CURRENT_AMPERE was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please create a bug report at https://github.com/alandtse/tesla/issues
SOURCE_TYPE_GPS was used from tesla_custom, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/alandtse/tesla/issues

```

**Comment by skipishere** [comment] 2024-01-10 23:31
Duplicate of https://github.com/alandtse/tesla/issues/810

**Closed by skipishere** 2024-01-10 23:31 UTC
