### ISSUE TITLE
Tesla API-warning

### ISSUE THREAD

**Issue by frederikvoGIT** [alandtse/tesla#905] opened 2024-03-14 07:45 UTC
Logger: homeassistant.components.climate
Bron: components/climate/__init__.py:361
integratie: Klimaat (documentation, issues)
First occurred: 00:47:36 (1 gebeurtenissen)
Laatst gelogd: 00:47:36

Entity None (<class 'custom_components.tesla_custom.climate.TeslaCarClimate'>) implements HVACMode(s): heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/alandtse/tesla/issues
![afbeelding](https://github.com/alandtse/tesla/assets/144563140/7c9441a4-11b2-43ee-8b40-41b3d16a63ee)

**Comment by skipishere** [comment] 2024-03-14 09:20
Duplicate of https://github.com/alandtse/tesla/issues/854

**Closed by skipishere** 2024-03-14 09:20 UTC
